// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Task_Web_API.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20250125062601_AddIndexAndSeedData")]
    partial class AddIndexAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_Web_API.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_ToDoItems_Title");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25a698cd-9945-41ea-8046-1808018794fa"),
                            CreatedAt = new DateTime(2025, 1, 25, 6, 26, 1, 504, DateTimeKind.Utc).AddTicks(3400),
                            Description = "Milk, Eggs, Bread",
                            IsCompleted = false,
                            Title = "Buy Groceries"
                        },
                        new
                        {
                            Id = new Guid("1f4e7986-d5f5-4336-b766-8cfd978f1a63"),
                            CreatedAt = new DateTime(2025, 1, 25, 6, 26, 1, 504, DateTimeKind.Utc).AddTicks(3400),
                            Description = "Finish coding and testing",
                            IsCompleted = false,
                            Title = "Complete Project"
                        },
                        new
                        {
                            Id = new Guid("91bc5ab7-42a3-4f16-8579-4a34b4d70fbb"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exercise for 30 minutes",
                            IsCompleted = false,
                            Title = "Workout"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
