// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Task_Web_API.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20250127093155_UpdateEntities")]
    partial class UpdateEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_Web_API.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_ToDoItems_Title");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7eec7fc7-ed0c-4a57-928c-062d469258f1"),
                            CreatedAt = new DateTime(2025, 1, 27, 9, 31, 55, 506, DateTimeKind.Utc).AddTicks(9100),
                            Description = "Milk, Eggs, Bread",
                            IsCompleted = false,
                            Title = "Buy Groceries"
                        },
                        new
                        {
                            Id = new Guid("dec2f8cf-f6d6-4e3d-b4a1-9e4c49d15900"),
                            CreatedAt = new DateTime(2025, 1, 27, 9, 31, 55, 506, DateTimeKind.Utc).AddTicks(9100),
                            Description = "Finish coding and testing",
                            IsCompleted = false,
                            Title = "Complete Project"
                        },
                        new
                        {
                            Id = new Guid("a9e16d96-574b-44bc-b078-cd42da04e4fc"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exercise for 30 minutes",
                            IsCompleted = false,
                            Title = "Workout"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
